# Builds the three Nano Banana Pro prompts and checks each is 10,000-13,000 characters.
import pathlib

PRODUCT = """PRODUCT FIDELITY LOCK — @image2 IS THE ONLY SOURCE OF TRUTH FOR THE BOTTLE. The perfume bottle is the COMMODITY "Spice" bottle exactly as photographed in @image2, reproduced one-to-one with zero redesign. Its silhouette, proportions, materials, label layout and typography are locked and may not be reinterpreted, simplified, stylised, stretched, shortened, beautified or "improved". Only the light falling on it changes, never the object itself.
Silhouette and proportions (locked): a straight-walled cylindrical glass flacon with a flat, thick base and softly radiused shoulders, topped by a separate cylindrical cap. Overall height-to-width ratio of the complete bottle (cap included) is approximately 1.83 : 1. The cap diameter is approximately 64 percent of the body diameter, sits perfectly centred and coaxial on the body, and the cap height is approximately 19 percent of the overall bottle height. The body is a true cylinder with parallel sides — not tapered, not faceted, no ribs. The shoulder radius is small and tight, the base edge is crisp with a very slight chamfer, and the glass base is visibly thick (roughly one-tenth of the body height) when seen at the bottom edge.
Body material: dark smoked / black-tinted glass, glossy, transparent only at its edges and thinnest points — where the glass is seen edge-on along the left and right silhouette and at the shoulder, a thin band of deep smoky brown-black translucency is visible, with the darker liquid column inside reading as a slightly denser black.
Cap: solid black cylinder in satin black anodized / brushed metal finish with very fine horizontal (circumferential) brushing lines, a gently bevelled top edge, and a matte-satin sheen that produces a soft streaked highlight following the brushing direction rather than a mirror reflection. No logo on the cap. No gap or visible collar between cap and shoulder other than the fine seam seen in @image2.
Label (locked, must be pixel-faithful to @image2): a single rectangular matte black paper label on the front face, running from just below the shoulder down to roughly three-quarters of the body height, covering almost the full front width with a narrow strip of glossy glass visible at the left and right. The matte black label is slightly lighter and flatter than the glossy glass around it, so its rectangular edge is readable by a change in sheen. Typography printed in clean white: on the left-centre of the label, the brand word "COMMODITY" set in small, widely tracked, light-weight capitals; directly beneath it, the large product name "Spice" set in a bold high-contrast serif typeface with a capital S and lowercase "pice", left-aligned under "COMMODITY" and occupying roughly 60 percent of the label width. Along the right edge of the label is a narrow vertical column containing a tiny 2 x 2 dot pictogram (four small white dots, one rendered as a small ring) at the top, and below it two lines of very small white sans-serif text rotated 90 degrees reading top to bottom: "Scent Space: Expressive" and "For me and the many around me". Spelling must be exact: C-O-M-M-O-D-I-T-Y and S-p-i-c-e. No other text, no extra logos, no barcode, no invented words, no mirrored text, no warped letterforms.
Only ONE bottle exists in the frame. No duplicates, no reflections that read as a second bottle, no extra caps, no packaging box."""

INTEGRATION = """INTEGRATION REALISM — WHAT MAKES THIS A PHOTOGRAPH, NOT A COMPOSITE. The bottle is physically present in the pigment, so it must obey the same light as every grain in @image1. (1) Light direction match: the single key light in @image1 comes from the upper-right of frame at a low raking angle; therefore the brightest specular highlight on the glossy black glass appears as a long, soft-edged, slightly curved highlight strip on the side of the bottle facing upper-right, the brushed cap shows its streaked highlight on the same side, and the opposite side of the bottle falls into deep black with no competing highlight. (2) Contact and occlusion: where the bottle meets the powder, the pigment piles up against the glass in small soft drifts and the bottle slightly displaces and compresses the powder around it; a tight, dense, near-black-red contact shadow sits exactly in the seam between glass and powder, then a longer, softer cast shadow falls toward the lower-left, matching the direction, length ratio, edge softness and deep oxblood colour of the shadows already cast by the powder clumps in @image1. (3) Colour bounce: the black glass is not neutral black in this world — every reflective surface picks up the environment, so the glossy body reflects a blurred, darkened crimson version of the surrounding pigment and plaster, giving the black glass a deep red-black sheen along its curvature, strongest near the bottom where it faces the red ground; the satin cap shows a faint red glow in its lower half from the red bounce light. (4) Pigment on the product: a light, uneven dusting of the same fine red pigment rests on the upper-facing surfaces of the bottle and cap — individual grains and tiny clumps, a few fingerprint-free smudges of red powder on the glass edge, grains caught in the cap seam — each grain lit by the same raking key light with its own micro-shadow. Dust is sparse enough that the label typography remains fully legible. (5) Sharpness and grain match: the bottle has exactly the same resolution, micro-contrast, fine grain and slight softness as the powder at the same focal distance; it must not be cleaner, sharper, more saturated or more contrasty than its surroundings."""

SCENE_CORE = """SCENE TRUTH — @image1 DEFINES THE WORLD. @image1 is a monochromatic crimson still-life: a diagonal swath of very fine dry red pigment powder (like ground chili, paprika or raw powder pigment) running from the top-left corner down to the bottom-right of the frame, scattered over a flat surface of red-painted, hand-troweled plaster. The powder band has crumbling, clumped edges — small rounded aggregates, pebble-sized clumps, loose sifted grains, feathered drag marks where the powder has been swept by hand, and a few isolated crumbs that have rolled off the swath onto the bare surface. The plaster underneath is matte with a fine sandy tooth, shallow pits, soft trowel undulations and thin hairline cracks, especially visible in the lower-left and right areas. Palette is a single hue family: midtones around crimson #B3121C, lit highlights on clump tops around bright scarlet #D9222C, half-shadows around #7A0A10, deep shadows and crevices around oxblood #3E0407, with no other colour anywhere — no orange shift, no pink, no magenta, no neutral greys. The image reads as one deep saturated red monochrome, with tonality created purely by light and shadow on texture."""

TECH_SCENE = """Camera and lens (taxonomy-anchored): medium-format digital capture in the manner of a Hasselblad X2D / Fujifilm GFX with a 120mm macro prime, delivering extremely smooth tonal gradation within the reds, high micro-contrast on every powder grain and no visible digital noise. Light source: a single large diffused strobe through a softbox (studio strobe through a softbox, ~5500K) placed at the upper-right of frame at a low raking angle of roughly 20 to 25 degrees above the surface, with no fill other than gentle red bounce from the set itself (single source, no fill). Shadows are soft-edged but clearly directional, falling toward the lower-left; every clump carries a lit upper-right face and a shaded lower-left face, which is what sculpts the powder into relief. Highlights are controlled and never clipped; the brightest red stays fully saturated. Colour grade: high-saturation commercial pop restricted to a monochrome crimson palette, with a natural darker vignette toward the bottom-left and lower corners exactly as in @image1. Effects: fine film-like grain consistent across the whole frame, natural vignette, no lens flare, no chromatic aberration, no haze, no bokeh balls, no added particles in the air."""

NEGATIVE = """NEGATIVE / EXCLUSIONS. Do not alter the bottle's shape, proportions, cap size, cap height, label size, label position, typeface or text. Do not invent a new bottle or a generic perfume flacon. No floating bottle, no missing contact shadow, no shadow pointing in a different direction than the powder shadows, no second light source, no rim light that does not exist in @image1, no studio-white reflections on the glass that do not belong to this red world. No plastic, waxy or CGI look, no bloom. No gibberish, misspelled, duplicated, mirrored or warped label text. No extra bottles, no props, no hands, no flowers, no spices other than the red powder, no droplets, no smoke. No change to the established crimson monochrome grade — no orange, pink, purple or blue cast, no desaturation, no neutral grey surfaces. No text overlays, watermarks, borders or logos added to the image."""

V1 = f"""A real commercial hero still-life photograph for the fragrance COMMODITY Spice, captured in camera on a professional set — not an illustration, not a 3D render, not a composite. Recreate the scene of @image1 exactly — same overhead camera position, same framing, same diagonal powder swath, same plaster surface, same light, same crimson monochrome grade — and place the perfume bottle from @image2 into it as if it had been physically laid into the powder on set before the shutter was pressed. Output: portrait 2:3, 2K, photorealistic.

{SCENE_CORE}

CAMERA, FRAMING AND COMPOSITION FOR THIS SHOT. The camera is directly overhead, a true 90-degree top-down flat-lay, sensor plane parallel to the plaster surface, identical to @image1. {TECH_SCENE} Aperture around f/8 (moderate depth of field): because the bottle rises a few centimetres above the surface, the label plane and the powder immediately around the bottle are tack-sharp, while the most distant corners of the swath keep the same subtle softness they have in @image1. Keep every compositional element of @image1 in its original place — the swath's angle, its width, the cracks in the plaster, the clumps at the top-left and the trailing edge at the bottom-right — so that the background is recognisably the same photograph.

PLACEMENT OF THE BOTTLE. Because the camera looks straight down, the bottle is lying on its side, resting in the powder in the centre of the frame, its long axis aligned with the diagonal direction of the swath: the cap points toward the upper-left, the thick flat base points toward the lower-right. The bottle occupies roughly 55 to 60 percent of the frame height along that diagonal, sitting slightly above the geometric centre, on the swath's centreline, so that powder is visible on both of its long sides and bare red plaster is visible in the upper-right and lower-left corners. The front label faces straight up at the camera, perfectly readable, with "COMMODITY" and "Spice" running along the bottle's long axis as they would when a cylinder is laid on its side — the text is rotated with the bottle, not re-set horizontally. The cylinder rests on the powder with a slight settle: its underside sinks 2 to 3 millimetres into the soft pigment, small drifts of powder are pushed up against both long sides of the glass, and a little ridge of compressed powder sits against the base. The cylindrical body shows correct foreshortening for a horizontal cylinder seen from above: the label appears flat and centred, while the glass curves away on both sides into the darkness, with the curvature readable through the highlight gradient.

LIGHT ON THIS BOTTLE IN THIS ORIENTATION. The raking softbox from the upper-right lands across the upper-right flank of the lying cylinder, so a long soft specular highlight strip runs parallel to the bottle's long axis along that flank — a deep red-tinted reflection of the bright powder, with a cleaner, brighter core where the softbox itself reflects. The lower-left flank of the bottle falls into near-black with only a faint crimson reflection of the ground. The brushed cap's circumferential brushing lines appear as fine parallel lines across the cap, with the brushed highlight streaking along the upper-right side. The bottle casts a soft shadow onto the powder toward the lower-left, about one-third of the bottle's width in length, deeper and denser near the glass and feathering out, matching the shadows cast by the larger clumps in @image1. The matte label receives a broad, gentle gradient — slightly brighter toward the upper-right — that keeps the white type fully legible.

{PRODUCT}

{INTEGRATION}

FINISH. The final image should look like an unretouched RAW frame from a medium-format camera on a professional perfume campaign, ready for a light manual retouch: crimson monochrome world, a single real black bottle lying in the pigment, light, shadow, reflection and grain in perfect agreement. Portrait 2:3 aspect ratio, 2K resolution, photorealistic.

{NEGATIVE}"""

V2 = f"""A real commercial hero still-life photograph for the fragrance COMMODITY Spice, captured in camera on a professional set — not an illustration, not a 3D render, not a composite. This is a slight variation of @image1: the same red pigment world, same plaster, same light quality and same crimson monochrome grade, but the camera has been lowered from overhead to a three-quarter high angle and the perfume bottle from @image2 stands upright in the scene, so the product reads as a proud, vertical hero. Output: portrait 2:3, 2K, photorealistic.

{SCENE_CORE}

CAMERA, FRAMING AND COMPOSITION FOR THIS SHOT. The camera looks down at the set from a high angle of roughly 50 degrees above the surface (three-quarter overhead), positioned so that the diagonal powder swath from @image1 now recedes from the lower-left foreground toward the upper-right background, becoming a leading line that carries the eye to the bottle. {TECH_SCENE} For this angle the same 120mm macro prime is stopped to around f/5.6 (shallow-to-moderate depth of field): the bottle and the powder immediately at its base are tack-sharp, powder clumps in the near foreground soften gently, and the plaster and swath behind the bottle fall off into a smooth, creamy, round-bokeh red blur — no bokeh balls, just soft texture dissolving with distance. The far background darkens to a softly vignetted oxblood plane behind the bottle.

PLACEMENT OF THE BOTTLE. The bottle stands upright on its flat base, slightly to the right of centre on the vertical thirds line, with its base at about 62 percent of the frame height from the top, planted at the right-hand edge of the powder swath where the pigment meets bare plaster. The bottle occupies roughly 50 percent of the frame height, leaving generous breathing room of dark red above the cap. The label faces the camera squarely (front face rotated no more than 5 degrees toward camera-left), so "COMMODITY" and "Spice" are fully legible and horizontal. Because the camera looks down at 50 degrees, the cylinder shows natural perspective: the top of the cap is visible as a slightly elliptical disc, the label reads with a gentle vertical foreshortening, and the base ellipse is slightly wider than the shoulder ellipse — all optically correct, while the real proportions of @image2 remain intact. The base sinks a few millimetres into a small mound of pigment that has been pushed up around it, with loose grains scattered against the glass and a soft ridge of powder curling against the left side of the base where the swath meets it.

LIGHT ON THIS BOTTLE IN THIS ORIENTATION. The same single raking softbox comes from the upper-right and slightly behind the set, now acting as a side-back key relative to this camera angle: it draws a long, vertical, soft-edged specular highlight down the right edge of the glossy black body from shoulder to base, a curved highlight across the right side of the shoulder, and a streaked brushed-metal highlight down the right side of the cap and along its bevelled top edge. The front matte label receives soft, slightly falling-off light, brighter at its right edge and gently darker at the left, while the white typography stays crisp and legible. The left side of the bottle falls into deep red-black, separated from the background only by a faint crimson reflection of the surrounding pigment. The bottle casts a soft, elongated shadow across the powder toward the lower-left foreground, matching the direction of every clump shadow in the scene; the contact shadow at the base is dense and tight. The glossy body reflects a blurred, darkened band of the red powder swath near its bottom third.

{PRODUCT}

{INTEGRATION}

FINISH. The final image should look like an unretouched RAW frame from a medium-format camera on a professional perfume campaign, ready for a light manual retouch: the same crimson pigment world as @image1, seen from a lower, more heroic angle, with one real upright black bottle anchored in the powder and lit by the same single raking light. Portrait 2:3 aspect ratio, 2K resolution, photorealistic.

{NEGATIVE}"""

V3 = f"""A real macro detail photograph for the fragrance COMMODITY Spice, captured in camera with a true macro lens on a professional set — not an illustration, not a 3D render, not a composite. This is an extreme close-up of the bottle from @image2 lying in the red pigment of @image1, framed so tight that the materials themselves become the subject: individual red pigment grains, the fine brushing of the black cap, the satin-matte paper label, the crisp white printed letters and the deep glossy smoked glass, all sharing one world of light. Output: portrait 2:3, 2K, photorealistic.

{SCENE_CORE}

CAMERA, FRAMING AND COMPOSITION FOR THIS SHOT. Medium-format digital capture with a 120mm macro prime at roughly 1:2 to 1:1 magnification (macro close-up crop), camera at a low grazing angle of about 25 degrees above the surface, looking along the bottle which lies on its side in the powder, exactly as it would in the overhead hero shot. Aperture f/5.6 at macro distance gives a razor-thin plane of focus: the sharp plane sits on the label's upper edge and the shoulder-to-cap junction, while pigment grains in front of and behind that plane fall into soft, creamy, round-bokeh blur. Lighting is the same studio strobe through a large softbox at the upper-right, raking low across the materials at ~5500K, single source with only red bounce fill, so every grain throws its own tiny shadow toward the lower-left. Colour grade is the same high-saturation crimson monochrome as @image1, with fine grain consistent across the frame and a soft natural vignette.

FRAMING OF THE DETAIL. The visible area of the real bottle is only about 6 centimetres wide. The frame contains, from upper-left to lower-right along a gentle diagonal: the lower third of the brushed black cap at the top-left, the hairline seam where cap meets glass, the tight radiused glass shoulder, and the top-left region of the matte black label, where the white word "COMMODITY" and the full word "Spice" are both completely inside the frame, sharp, correctly spelled and printed in the exact typefaces of @image2 — small tracked light capitals above, bold high-contrast serif below. Because the bottle lies on its side, the text runs along the bottle's long axis and rises diagonally through the frame. The rest of the frame is red pigment: in the foreground, out-of-focus clumps of powder form a soft crimson blur along the bottom edge; around the glass, sharp grains pile against the bottle in tiny drifts; behind the bottle, the plaster and powder dissolve into a smooth deep-red bokeh that darkens toward the top-right.

MATERIAL DETAIL AT MACRO SCALE (this is the point of the image). Pigment: thousands of individual particles visible, irregular, slightly crystalline, with tiny bright scarlet highlights on their upper-right faces and oxblood shadows on their lower-left faces; some grains are stuck to the glass and label, a few rest on the white letters without hiding them, a thin film of red dust has settled in the cap seam. Cap: satin black anodized metal with fine, regular circumferential brushing lines clearly resolved, a soft streaked highlight running across the brushing, a faint red glow in the lower half from bounce, and the precise bevel at its edge. Glass: deep smoked black, glossy, with a long soft specular highlight sweeping over the shoulder curvature and a thin translucent dark-brown rim where the glass is seen edge-on, through which the red powder behind shows darkened and slightly refracted; the glossy surface mirrors a blurred, darkened crimson image of the pigment around it. Label: matte black uncoated paper stock with a subtle fibrous tooth visible at this scale, a clean die-cut edge that sits a fraction of a millimetre proud of the glass and catches a hairline highlight, and white ink letterforms with sharp edges and the very slight ink spread of real printing. No fingerprints, no scratches, no bubbles.

{PRODUCT}

{INTEGRATION}

FINISH. The final image should look like an unretouched RAW macro frame from a medium-format camera on a professional perfume campaign: tactile, sensory and believable, every material resolved, the bottle unmistakably the exact COMMODITY Spice bottle from @image2, lying in the crimson world of @image1. Portrait 2:3 aspect ratio, 2K resolution, photorealistic.

{NEGATIVE}"""

for name, text in [("v1_exact_scene", V1), ("v2_hero_variation", V2), ("v3_macro_detail", V3)]:
    pathlib.Path(f"{name}.txt").write_text(text)
    n = len(text)
    print(f"{name}: {n} chars", "OK" if 10000 <= n <= 13000 else "OUT OF RANGE")
