# Round 4: harmonise a hand-built composite. @image1 = composite plate (bottle already placed at true scale in the
# original photo), @image2 = bottle reference, @image3 = original hand photo. Checks 10,000-13,000 chars.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)

P = f"""A real, unretouched-looking photograph for the fragrance COMMODITY Spice. This is a FINISHING PASS on a photo composite, done the way a high-end retoucher would do it: @image1 is the plate — the original photograph @image3 with the real COMMODITY Spice bottle already placed in the woman's palm at its true size and position. Your job is to make @image1 look like one single photograph taken in one moment: the hand really holding the bottle, the bottle really lit by the scene, nothing pasted. Portrait 4:5, 2K, photorealistic.

WHAT IS LOCKED (do not change). (1) The framing, crop and camera of @image1: the forearm entering from the left at the vertical middle of the frame, the black space above and below, the bangles at the wrist, the two fine chains hanging from the palm, the coin chains on the right, the maroon-black backdrop with its faint vertical fabric texture. (2) The position and size of the bottle exactly as in @image1: standing upright in the palm, centred where the apple used to be, about 1.6 times the apple's height in @image3 and narrower than the palm. Do not enlarge it, do not shrink it, do not move it, do not tilt it. (3) The bottle's design from @image2: shape, proportions, cap, label layout and text. (4) The red colour world of @image3: only red and black, no white, no orange, no neutral tones. (5) No rings on any finger.

WHAT YOU MUST FIX.
A — REMOVE THE APPLE COMPLETELY. Any faint outline, edge, curve or red sheen of the apple that remains around the bottle in @image1 is erased and replaced by the backdrop and the palm exactly as they would look without the apple. Nothing round remains behind the bottle.
B — THE HAND HOLDS THE BOTTLE, SENSUALLY. Keep the same arm, wrist angle and elegant pose as @image3, but the hand now genuinely holds the bottle: the palm cups the base, and the softly touching fingers curl up around the lower third of the glass in a slow, tender, intimate gesture, almost a caress. The pads of the fingertips rest lightly against the glass and flatten very slightly where they touch it; the long glossy almond nails glide along the curve of the bottle; one fingertip just grazes the lower edge of the label. The thumb rests against the near side of the base. The grip is loose and relaxed, never a fist, never stiff, knuckles soft. Where the fingers pass in front of the bottle they cover the glass behind them. The fine chains that lie over the palm in @image3 now also drape across the base of the bottle.
C — REAL WEIGHT AND CONTACT. The base of the bottle sits in the hollow of the palm with no gap; the soft flesh of the palm bulges very slightly around the base; a dense, soft, dark-red contact shadow fills every seam where glass meets skin and where fingers meet glass. The bottle casts a soft shadow onto the palm and the fingers toward the lower right. The wrist carries the weight naturally.
D — REAL LIGHT ON THE BOTTLE. The only light is the soft red light of @image3 from above, slightly in front and camera-left. The bottle is opaque glossy black glass: it stays mostly black and dark, blending into the shadows. Its left edge receives one long, soft, dull red highlight running from the shoulder down to the fingers; its shoulder and the bevel of the brushed cap catch thin dull red glints; its right half falls away into black that merges with the backdrop. The glossy glass reflects a dim, blurred red image of the palm and fingertips near its base — reflections only, never transparency. The matte label is lit softly from the left; under this deep red light the white ink of "COMMODITY" and "Spice" reads as a muted salmon-red, about as bright as the lit skin of the palm, never white, never glowing, but crisp and legible.
E — ONE CAPTURE. The bottle gets exactly the same lens softness, depth of field, fine luminance grain, red colour cast and contrast as the hand next to it. Its edges are as soft as the finger edges: no cut-out line, no halo, no sharper outline, no cleaner surface than the skin.

JEWELLERY AND BACKDROP DETAIL. The bangles at the wrist are thin polished metal hoops stacked loosely, each catching one thin red-gold highlight on its upper edge and falling to dark red underneath; they move with the wrist as it takes the bottle's weight. The two fine chains are delicate cable chains a millimetre thick, each link catching a tiny glint; where they cross the bottle's base they lie flat on the glass with a hairline shadow and a tiny dim reflection. The coin chains on the right keep their hammered discs, each disc with a soft red-gold rim light and a darker centre. The backdrop keeps its faint vertical fabric folds, brightest just behind the hand and falling to near-black at the corners; the area where the apple was is continuous backdrop with no patch, smudge or seam.

HAND AND SKIN. The same hand as @image3: same skin colour (luminous coral-red to vermilion where lit, #F0463C highlights, #D42A28 midtones, dark red #8C1014 in creases), same finger length, same long glossy almond nails, same lacquer. Real skin: fine pores on the back of the hand and wrist, creases across the palm and at each knuckle, slight translucency at the fingertips, cuticles, a soft natural sheen — not waxy, not airbrushed. One hand, five fingers, natural joints, no extra or merged fingers, no rings.

{PRODUCT}

CAMERA AND FINISH. Same capture as @image3: full-frame digital, about 85mm, eye-level, f/4; hand and bottle sharp, chain ends and bangles slightly soft; faint fine luminance noise in the shadows; soft black vignette. The result must be indistinguishable from an unretouched frame shot on the set of @image3, with the real bottle of @image2 resting in the model's hand: one light, one colour, one grain, one moment, one whole image. Portrait 4:5, 2K, photorealistic.

NEGATIVE / EXCLUSIONS. No apple or apple outline. No change of bottle size, position, angle, shape, proportions, cap, label layout or text; no generic bottle. No oversized bottle. No floating bottle, no gap under the base, no missing contact shadow. No bright, white or glowing label; no clean studio product look; no bottle brighter or sharper than the hand; no halo, outline or pasted edge. No transparency in the glass. No second light source, no white, blue or pink light, no washed-out or flat lighting — keep the deep red, low-key contrast of @image3. No change of arm direction: the arm always enters from the left. No rings. No extra, missing or merged fingers, no distorted nails, no fist. No plastic or waxy skin, no CGI look, no bloom. No misspelled, mirrored or warped text. No extra bottles, no new props, no face. No text overlays, watermarks or borders."""

pathlib.Path("v1_harmonise.txt").write_text(P)
n = len(P); print(f"v1_harmonise: {n} chars", "OK" if 10000 <= n <= 13000 else "OUT OF RANGE")
sys.exit(0 if 10000 <= n <= 13000 else 1)
