# Direct generation: @image1 = original spice-drawer scene, @image2 = bottle. Two framings. 10,000-13,000 chars each.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)

SCENE = """THE SCENE — @image1, KEEP IT. @image1 is the background and must be recognisably the same photograph: a straight top-down view into an antique wooden type-case used as a spice drawer, its grid of square compartments rotated about 30 degrees so the long wooden dividers run diagonally from the lower-left to the upper-right. Same dividers (dark, worn, oiled wood with rounded edges and small nicks), same spices in the same compartments and the same arrangement: saffron threads and pale ginger at the top, golden cumin and turmeric powders at the upper-left, burnt-orange paprika at the upper-right, dark caraway/cumin seeds in the centre-top compartment, vivid brick-red paprika powder in the centre-right compartment, pale green-white peppercorns in the large lower-centre compartment, cinnamon-brown powders at the left and lower-right, star anise pods and cinnamon sticks at the bottom. Same warm tungsten light (about 2900K) from the upper-left, slightly raking: every mound is bright on its upper-left flank and falls into warm brown shadow on its lower-right; every divider throws a short soft shadow to its lower-right. Same rich warm palette of saffron red, ochre, cinnamon, umber and cream. Same medium-format still-life look, f/8, fine film-like grain. Do not redesign the drawer, do not invent new compartments, do not change the wood colour, do not add a table or any background outside the drawer."""

BOTTLE_GLASS = """THE GLASS — BLACK AND NOT TRANSPARENT. The bottle's glass is BLACK: solid, opaque, glossy black, like polished obsidian or black lacquer. It is NOT transparent and NOT tinted: no amber, golden, brown or smoky see-through glass, no liquid visible, no spices visible through it, no light glowing through the shoulder or the base. Under the warm lamp it shows only surface effects: one long, soft, warm golden highlight along its upper-left side, a soft warm curved highlight on the rounded shoulder, a thin warm line on the chamfered edge of the base, and dim, blurred, darkened reflections of the neighbouring spices on its curved surface. Everywhere else it is deep, dense, glossy black."""

PLACEMENT = """THE BOTTLE LIES ON TOP OF THE SPICES. The perfume bottle from @image2 lies on its side on top of the spice drawer, its long axis parallel to the diagonal wooden dividers, its thick base toward the lower-left and its cap toward the upper-right, centred on the brick-red paprika compartment and resting across the divider between the paprika and the caraway seeds. Its size is real: a 100ml bottle about 12 cm long, so its length is about one and a half compartments — it never covers more than two compartments. The label faces up toward the camera, so "COMMODITY" and "Spice" read along the length of the bottle. Heavy glass on loose spice: it sinks a few millimetres into the paprika, pressing a shallow trough with a soft raised lip along its lower-right side; it rests on the top edge of the wooden divider it crosses; at the base end a few peppercorns are pushed against the glass. Dense warm-brown contact shadows fill every line where glass meets spice or wood, and a soft cast shadow falls to the lower-right, matching the divider shadows."""

SPICES_ON = """SPICES OVER THE BOTTLE — REALISTIC, AS IF SPILLED ON SET. The bottle has been lightly buried and dusted by the stylist's hands: a thin, uneven drift of brick-red paprika powder has been sprinkled across the glass shoulder and onto the side of the cap, thicker along the top ridge of the lying cylinder and thinning toward its sides, with loose grains rolling down the curve and collecting in the contact line below; a small pinch of paprika lies on the upper corner of the label without covering any letters; seven or eight dark caraway seeds rest on the glass near the cap, each with its own tiny shadow; two pale peppercorns sit against the glass near the base, one balanced on the base's chamfered edge; a faint dusting of golden cumin powder rests on the upper surface of the body near the base. Every grain and seed on the bottle is lit by the same warm lamp from the upper-left, bright on its upper-left side, with a tiny dark shadow on the glass to its lower-right. The powder on the glossy glass shows its own matte texture against the black, exactly like real spice dust on black glass. The label text "COMMODITY" and "Spice" stays fully visible."""

REAL = """INTEGRATION. The bottle is photographed in the drawer, not pasted: same sharpness, depth of field, fine grain, warm colour cast and contrast as the spices next to it; edges as natural as the edges of the wooden dividers, never cut out or haloed; the white label type reads as a soft warm cream under tungsten light, crisp but never glowing or brighter than the brightest peppercorn. Glossy black glass reflects the warm surroundings only on its surface."""

NEG = """NEGATIVE / EXCLUSIONS. No transparent, tinted, amber, golden, brown, smoky or clear glass; no glow inside the bottle; nothing visible through the glass. No change of the drawer, the compartments, their spices or the light of @image1; no new background, no table, no wider room. No floating bottle, no missing contact or cast shadow, no shadow in the wrong direction. No oversized bottle. No spice covering the label text. No change of the bottle's shape, proportions, cap, label layout or text; no generic bottle. No cool, white or neutral light, no studio product look, no halo or pasted edge. No misspelled, mirrored or warped text. No extra bottles, no hands, no props other than spices. No text overlays, watermarks or borders."""

def build(intro, framing):
    return "\n\n".join([intro, SCENE, framing, BOTTLE_GLASS, PLACEMENT, SPICES_ON, REAL, PRODUCT,
        "FINISH. Indistinguishable from an unretouched frame shot on the set of @image1 with the real bottle of @image2 lying in the drawer: one lamp, one colour, one grain, one moment, one whole image. Portrait 4:5, 2K, photorealistic.", NEG])

A = build("""A real still-life photograph for the fragrance COMMODITY Spice: the spice drawer of @image1 with the real COMMODITY Spice bottle of @image2 lying on top of the spices, photographed together in one shot by a world-class still-life photographer. Not an illustration, not a render, not a composite. Portrait 4:5, 2K, photorealistic.""",
"""FRAMING. Top-down, exactly the camera position of @image1, the whole drawer grid as in @image1, recomposed to a 4:5 portrait crop with the bottle in the centre of the frame. All the surrounding compartments stay visible around it — saffron and ginger at the top, the star anise and cinnamon sticks at the bottom, the cinnamon-brown powders at the left and right edges — so the bottle reads as one object resting inside the full drawer.""")

B = build("""A real close-up still-life photograph for the fragrance COMMODITY Spice: the spice drawer of @image1 with the real COMMODITY Spice bottle of @image2 lying on top of the spices, photographed closer by a world-class still-life photographer. Not an illustration, not a render, not a composite. Portrait 4:5, 2K, photorealistic.""",
"""FRAMING. Same top-down camera as @image1, but closer: a 120mm macro view of the centre of the same drawer, showing only the bottle and the compartments directly around it — the caraway seeds above, the brick-red paprika under and beside it, the peppercorns below-left, the cinnamon-brown powder at the lower-right, and the dark wooden dividers between them, exactly as they look in @image1, only larger. The bottle fills about two-thirds of the frame width along its diagonal, completely inside the frame. Every seed, grain and wood fibre is resolved in close-up detail.""")

ok=True
for n,t in [("v3_gen_full",A),("v3_gen_close",B)]:
    pathlib.Path(n+".txt").write_text(t); l=len(t); ok&=10000<=l<=13000; print(n,l,"OK" if 10000<=l<=13000 else "OUT")
sys.exit(0 if ok else 1)
