# Spice-drawer scene: harmonise a hand-built composite. @image1 = composite plate, @image2 = bottle, @image3 = original scene.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)

P = f"""A real, unretouched-looking still-life photograph for the fragrance COMMODITY Spice. This is a FINISHING PASS on a photo composite, done the way a high-end still-life retoucher would do it: @image1 is the plate — the original photograph @image3 of an antique wooden spice drawer, with the real COMMODITY Spice bottle from @image2 already laid on top of the spices at its true size, position and angle. Your job is to make @image1 look like one single photograph taken in one moment: the bottle physically lying in the drawer, lit by the same lamp, touching the same spices, nothing pasted. Portrait 4:5, 2K, photorealistic.

THE SCENE OF @image3 (locked, keep it exactly). A straight top-down view into an old wooden type-case used as a spice drawer, its grid of compartments rotated about 30 degrees so the long dividers run diagonally from the lower-left up to the upper-right. The dividers are dark, worn, oiled wood with soft rounded edges, small nicks and dust in the corners. Each compartment holds a different spice heaped into a soft mound: saffron threads, pale ground ginger, burnt-orange ground paprika and cayenne, golden ground cumin and turmeric-like powders, dark caraway or cumin seeds, a vivid brick-red paprika powder, pale green-white peppercorns, cinnamon-brown powder, star anise pods and cinnamon sticks at the bottom. Light: one warm tungsten source (around 2900K) from the upper-left, slightly raking, so every mound is bright on its upper-left flank and falls into warm brown shadow on its lower-right; each divider throws a short soft shadow onto the spice below-right of it; deep warm shadows in the corners of every compartment. Colour: a rich warm palette of saffron red, ochre, cinnamon, umber and cream, with no cool tones anywhere. Camera: medium-format still-life capture, around 100mm, top-down, f/8, everything sharp from corner to corner with slight softness only at the very edges, fine film-like grain.

WHAT IS LOCKED IN @image1 (do not change). (1) The whole drawer, all compartments, all spices, all dividers, the framing and the 4:5 crop. (2) The bottle's position, size and angle exactly as in @image1: lying on its side across the centre of the frame, its long axis parallel to the diagonal dividers, the thick base toward the lower-left and the cap toward the upper-right, its length about one and a half compartments. Do not enlarge it, shrink it, move it or rotate it. (3) The bottle's design from @image2. (4) The warm colour world of @image3.

WHAT YOU MUST FIX.
A — REAL CONTACT. The bottle is heavy glass lying on loose spice: wherever it lies over a compartment it sinks a few millimetres into the powder or seeds, the mounds are gently pressed and displaced along its underside, a few loose grains and seeds are pushed up against the glass, and where it bridges a wooden divider it rests on the divider's top edge. Dense, soft, warm-brown contact shadows fill every line where glass meets spice or wood. The cast shadow falls to the lower-right, matching the length, softness and warm brown colour of the divider shadows in @image3.
B — REAL LIGHT ON THE BOTTLE. The bottle is opaque glossy black glass. The warm lamp from the upper-left lays one long, soft, warm golden highlight along the upper-left side of the lying cylinder, from the shoulder to the base; the brushed black cap shows fine circumferential brushing with a soft warm streak on its upper-left edge; the lower-right side of the bottle falls into deep warm black. The glossy glass reflects, softly blurred and darkened, the warm colours of the spices beside it — saffron red, ochre and cinnamon — along its curved surface: reflections only, never transparency. The matte black label sits flat on top; under warm tungsten light its white type "COMMODITY" and "Spice" reads as a soft warm cream, crisp and fully legible, never bright white, never glowing.
C — SPICE ON THE GLASS. A light, uneven dusting of the neighbouring powders has settled on the upper surface of the bottle and in the seam of the cap: a few grains of red paprika and golden cumin on the glass, one or two seeds resting against the cap. Sparse enough that the label stays fully readable.
D — ONE CAPTURE. The bottle has exactly the same sharpness, depth of field, fine grain, warm colour cast and contrast as the spices around it. Its edges are as soft as the edges of the dividers: no cut-out line, no halo, no cleaner or sharper surface than the wood.

WHAT LIES UNDER AND AROUND THE BOTTLE. The bottle crosses the dark cumin-seed compartment near its cap end, the brick-red paprika compartment in its middle and the edge of the pale peppercorn compartment near its base, bridging the diagonal wooden divider between them. In the cumin compartment, a few dark seeds have rolled against the cap and lie half in its shadow. In the paprika compartment, the fine red powder is pressed into a shallow trough under the glass with a soft raised lip along the lower-right side, and a faint red haze of powder dusts the bottle's underside. At the base end, two or three pale peppercorns are nudged out of place, one resting against the glass with a tiny shadow. The neighbouring mounds keep their shape and lighting exactly as in @image3.

{PRODUCT}

MATERIAL DETAIL. Wood: dry, slightly fibrous, oiled dark brown, catching a warm sheen on rounded edges. Powders: fine, slightly clumped, with tiny cast shadows from every clump. Seeds and peppercorns: individual, each with its own small highlight and shadow. Glass: smooth, deep black, mirror-glossy, with the warm reflections described above. Cap: satin brushed black metal. Label: matte uncoated paper with a faint fibre texture and a clean die-cut edge.

FINISH. Indistinguishable from an unretouched frame shot on the set of @image3, with the real bottle of @image2 lying in the drawer: one lamp, one colour, one grain, one moment, one whole image. Portrait 4:5, 2K, photorealistic.

NEGATIVE / EXCLUSIONS. No change of bottle size, position, angle, shape, proportions, cap, label layout or text; no generic bottle; no oversized bottle. No floating bottle, no missing contact or cast shadow, no shadow in a different direction from the divider shadows. No transparency in the glass. No cool, white, blue or neutral light; no studio product look; no bottle brighter or sharper than the spices; no halo, outline or pasted edge. No change to the drawer, compartments or spices. No misspelled, mirrored or warped text. No extra bottles, no new props, no hands. No text overlays, watermarks or borders."""

pathlib.Path("v1_harmonise.txt").write_text(P)
n = len(P); print(f"v1_harmonise: {n} chars", "OK" if 10000 <= n <= 13000 else "OUT OF RANGE")
sys.exit(0 if 10000 <= n <= 13000 else 1)
