# Close-up: re-render a tight crop of the best drawer result. @image1 = close-up plate, @image2 = bottle, @image3 = original scene.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)

P = f"""A real close-up still-life photograph for the fragrance COMMODITY Spice, shot in camera with a 120mm macro lens on a medium-format body — not an illustration, not a render, not a composite. @image1 is the exact composition: a tight close-up of the COMMODITY Spice bottle lying diagonally on top of an antique wooden spice drawer. Re-shoot @image1 as a true high-resolution close-up: same framing, same bottle position and angle, same compartments and spices, same warm lamp — but with full close-up detail and with the bottle's glass corrected to solid, opaque black. Portrait 4:5, 2K, photorealistic.

THE GLASS — MOST IMPORTANT CORRECTION. The bottle is made of BLACK GLASS THAT IS NOT TRANSPARENT. It is solid, opaque, glossy black, like polished obsidian or black lacquer. Nothing can be seen through it anywhere: no amber, golden or brown glow inside, no liquid, no see-through ends, no spices visible through the glass, no light passing through the base or the shoulder. Any amber or transparent-looking area in @image1 — especially at the lower-left base end of the bottle — must become solid glossy black glass. The only things visible on the glass are surface reflections and highlights: one long, soft, warm golden highlight running along the upper-left side of the lying cylinder from shoulder to base, a soft warm curved highlight on the rounded shoulder, a thin warm line along the chamfered edge of the thick base, and dim, blurred, darkened reflections of the neighbouring spices — cumin brown, paprika red, peppercorn cream — mirrored on the curved surface. Under these reflections the glass is deep, dense black.

FRAMING (locked to @image1). Top-down close-up. The bottle lies on its side across the frame on a diagonal, its long axis parallel to the wooden dividers, base toward the lower-left (slightly cut by the left edge), cap toward the upper-right. The bottle fills most of the frame; around it: dark caraway/cumin seeds in the compartment above, ground spice in the compartment at upper-left, a fine brick-red paprika powder in the compartment to the right, pale green-white peppercorns below-left, cinnamon-brown powder at lower-right, the dark worn wooden dividers crossing between them. Do not zoom out, do not move or resize the bottle, do not change the arrangement.

CAMERA AND LIGHT. Medium-format digital, 120mm macro, top-down, f/8 for close-up depth: the label, the cap and the spices touching the bottle are tack-sharp; spices at the frame corners only very slightly softer. One warm tungsten lamp (about 2900K) from the upper-left, slightly raking: every seed, grain and peppercorn bright on its upper-left side with a tiny warm shadow to its lower-right; each wooden divider throws a short soft shadow to its lower-right; the bottle casts a soft warm-brown shadow onto the spices along its lower-right side. Fine film-like grain over the whole frame. Rich warm palette of umber, ochre, saffron red and cream — no cool tones.

CLOSE-UP DETAIL (render it all at full resolution). Cumin seeds: individual ridged seeds, each with fine longitudinal grooves and a tiny highlight. Paprika: velvety fine powder with small soft clumps and individual grains visible near the glass. Peppercorns: wrinkled spherical skins, cream to pale olive, each with its own highlight and cast shadow. Wood: dry, fibrous, oiled dark brown grain with small nicks, worn rounded edges catching a warm sheen, dust in the corners. Cap: satin black brushed metal with fine circumferential brushing lines resolved, a soft warm streak on its upper-left edge, a gently bevelled end. Label: matte black uncoated paper with fine fibre texture and a clean die-cut edge, white type rendered as soft warm cream under tungsten light — crisp, perfectly legible, never glowing.

CONTACT AND REALISM. The bottle is heavy and rests in the spices: it sinks a few millimetres into the paprika and cumin, pressing a shallow trough with a soft raised lip along its lower-right side; it rests on the top edge of the wooden divider it crosses; several peppercorns are nudged against the base, one touching the glass with a tiny contact shadow; a few cumin seeds lie against the cap. Dense, soft, warm-brown contact shadows fill every line where glass meets spice or wood. A light, uneven dusting of paprika and cumin powder rests on the upper surface of the glass and in the seam of the cap — sparse, so the label stays fully readable. Bottle and spices share exactly the same sharpness, grain, colour cast and contrast; the bottle's edges are as natural as the edges of the wood — no cut-out line, no halo.

LABEL AND TYPOGRAPHY AT CLOSE RANGE. Because the bottle lies on its side, the label runs along the bottle's length and its text runs diagonally with the bottle, rising from lower-left to upper-right, read along the cylinder exactly as printed in @image2: the small widely tracked capitals "COMMODITY" sit above the large bold high-contrast serif "Spice", both in warm cream; the narrow column along the label's edge holds the tiny four-dot pictogram and the two lines of very small rotated text "Scent Space: Expressive" and "For me and the many around me", fine but legible at this distance. The label's rectangular edge is visible as a change from matte paper to glossy black glass, with a hairline warm highlight along its die-cut edge. A few grains of paprika rest on the label surface without covering any letters.

COLOUR REFERENCES. Paprika around #B83A1C to #D2502A, cumin seeds #4A3420 to #7A5A3A, peppercorns #CFC6A0 to #E6DFC2, wood #3A2414 to #5C3A22 with warm highlights #8A6038, deepest shadows #1A0E06. The bottle glass reads #050403 to #0E0A07 under its reflections, its golden highlight around #C89A5A, never brighter than the brightest peppercorn.

{PRODUCT}

FINISH. Indistinguishable from an unretouched frame shot on the set of @image3, the real bottle of @image2 lying in the drawer, photographed close: one lamp, one colour, one grain, one moment. Portrait 4:5, 2K, photorealistic.

NEGATIVE / EXCLUSIONS. NO TRANSPARENT GLASS: no amber, golden, brown, clear or tinted see-through glass, no glow inside the bottle, no liquid visible, no spices visible through the glass, no light shining through the base. No change of bottle position, angle, size, shape, proportions, cap, label layout or text; no generic bottle. No zooming out, no wider view of the drawer. No floating bottle, no missing contact shadow, no shadow in a different direction from the divider shadows. No cool, white or neutral light; no studio product look; no halo or pasted edge. No misspelled, mirrored or warped text. No extra bottles, no new props, no hands. No text overlays, watermarks or borders."""

pathlib.Path("v2_closeup.txt").write_text(P)
n=len(P); print(f"v2_closeup: {n} chars", "OK" if 10000<=n<=13000 else "OUT OF RANGE")
sys.exit(0 if 10000<=n<=13000 else 1)
