# Four less-perfect, more photographic variations. @image1 = spice-drawer scene, @image2 = bottle. 10,000-13,000 chars each.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)
g = open(pathlib.Path(__file__).parent / "build_gen.py").read()
SCENE = re.search(r'SCENE = """(.*?)"""', g, re.S).group(1)
GLASS = re.search(r'BOTTLE_GLASS = """(.*?)"""', g, re.S).group(1)

REAL = """MAKE IT LOOK LIKE A REAL PHOTOGRAPH, NOT AI — LESS PERFECT, LESS CLEAN. This must look like an actual frame from a still-life shoot, shot on a medium-format film camera (Mamiya RZ67 or Hasselblad 500C/M) on Kodak Portra 400, scanned, not retouched. Real-photo cues that must be present: visible organic film grain across the whole frame including the bottle; slightly lifted, soft blacks rather than pure digital black; gentle, uneven light falloff and a natural lens vignette; focus that is crisp on the label but falls off softly and unevenly toward the frame edges, with the nearest and farthest spices slightly soft; very slight lens softness and mild halation around the brightest highlights; colours a touch muted and warm like film, not saturated or HDR. Imperfections, as on a real set: the spices are messy, not combed — irregular mounds with clumps, cracks and collapsed edges, loose grains, seeds and peppercorns scattered across the tops of the wooden dividers and into neighbouring compartments, a little powder dust on the wood; the wood has scratches, worn corners, old stains and dust in the joints. The bottle is not pristine: a soft fingerprint smudge and a few specks of dust on the glossy glass visible in the highlight, faint micro-scratches on the cap catching the light, the label edge very slightly lifted at one corner, the paprika dusting on the glass uneven and streaky where the stylist brushed it, some grains stuck in the label edge. The bottle does not sit perfectly straight: it is rotated a few degrees off the divider line and rolled a few degrees so the label faces the camera slightly obliquely. Nothing is symmetrical, nothing is perfectly centred. Avoid every AI look: no plastic smoothness, no over-sharpening, no glossy CGI reflections, no perfect gradients, no glowing edges, no hyper-saturated colours, no flawless surfaces."""

SPICE_ON = """SPICES ON THE BOTTLE — NATURAL, NOT DECORATIVE. Spices lie on the bottle the way they would after a real stylist scattered them by hand and the bottle settled: an uneven pinch of brick-red paprika powder on the shoulder and the side of the cap, thickest on the top of the curve and sliding off down the sides in loose streaks; a few loose grains clinging to the glass; several dark caraway seeds lying at random angles on the glass near the cap; one or two pale peppercorns resting against the base; a faint dusting of golden cumin powder on the body. The label text "COMMODITY" and "Spice" stays readable, with only a few grains near it. Each grain and seed is lit by the warm lamp from the upper-left with its own tiny shadow on the glass."""

CONTACT = """CONTACT AND WEIGHT. The bottle is heavy glass resting on loose spice and wood: it sinks a few millimetres into the powder, pushing up a small irregular ridge along one side; where it crosses a wooden divider it rests on its top edge; loose grains collect in the line where glass meets spice. Soft, dense, warm-brown contact shadows and a soft cast shadow to the lower-right, matching the divider shadows. The label type reads as a soft warm cream under tungsten light, never bright white."""

NEG = """NEGATIVE / EXCLUSIONS. No AI look: no plastic or waxy surfaces, no over-sharpened detail, no perfect symmetry, no perfectly combed spice mounds, no CGI product-render reflections, no HDR, no oversaturation, no glow. No transparent, tinted, amber, golden, brown, smoky or clear glass; nothing visible through the glass. No new background, no table or room outside the drawer unless the framing shows the drawer's edge. No floating bottle, no missing contact shadow. No oversized bottle — it is a real 100ml bottle about one and a half compartments long. No spice covering the label text. No change of the bottle's shape, proportions, cap, label layout or text; no generic bottle. No cool, white or neutral light. No misspelled, mirrored or warped text. No extra bottles, no hands. No text overlays, watermarks or borders."""

FIN = "FINISH. A real, scanned medium-format film frame from the set of @image1, with the real bottle of @image2 lying among the spices: one lamp, one colour, one grain, one moment, honest and imperfect. Portrait 4:5, 2K."

def build(intro, framing):
    return "\n\n".join([intro, SCENE, framing, GLASS, REAL, SPICE_ON, CONTACT, PRODUCT, FIN, NEG])

I = "A real still-life photograph for the fragrance COMMODITY Spice: the spice drawer of @image1 with the real COMMODITY Spice bottle of @image2 lying on the spices. Not an illustration, not a render, not a composite. Portrait 4:5, 2K."
V = {
"v4_1_topdown": build(I, "FRAMING — VARIATION 1, TOP-DOWN DRAWER. Straight top-down as in @image1, slightly closer than @image1 so about nine compartments are visible. The bottle lies on its side across the brick-red paprika compartment and the divider to the caraway seeds, cap toward the upper-right, slightly off the divider angle. The bottle sits a little right of and below centre, not perfectly centred."),
"v4_2_halfburied": build(I, "FRAMING — VARIATION 2, HALF-BURIED CLOSE. Top-down, closer: about four compartments visible. The bottle lies low in the paprika compartment, half sunk into the soft red powder so the powder rises around its lower edge and spills over the label's lower margin; its cap rests on the wooden divider and pokes into the caraway seeds, which have tumbled against it. The frame cuts the base end slightly at the left edge. Peppercorns visible in the lower-left corner."),
"v4_3_angled": build(I, "FRAMING — VARIATION 3, LOW ANGLE ACROSS THE DRAWER. The same drawer and spices, but the camera is lowered to about 35 degrees above the drawer, looking across the compartments, 100mm lens at f/4: the bottle lies on its side across two compartments in the foreground-middle, sharp; the compartments behind it fall into soft warm blur, the nearest peppercorns in the bottom of the frame are slightly out of focus. The wooden dividers recede in perspective. The warm lamp from the upper-left now also rims the top edge of the bottle and the tops of the spice mounds."),
"v4_4_detail": build(I, "FRAMING — VARIATION 4, MACRO DETAIL. Top-down macro, 120mm at about 1:3: the frame shows only the upper part of the bottle — the brushed black cap, the shoulder and the top of the label with \"COMMODITY\" and the full word \"Spice\" — lying in the paprika next to the caraway seeds, with the spice dust on the glass and cap shown up close: individual powder grains, seeds lying on the black glass, a fingerprint smudge in the highlight. The rest of the bottle runs out of the frame at the lower-left. Very shallow focus falls off along the bottle's length."),
}
ok=True
for n,t in V.items():
    pathlib.Path(n+".txt").write_text(t); l=len(t); ok&=10000<=l<=13000; print(n,l,"OK" if 10000<=l<=13000 else "OUT")
sys.exit(0 if ok else 1)
