# Four dynamic "award" shots: spices thrown / falling onto the bottle. @image1 = spice drawer, @image2 = bottle.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)
g = open(pathlib.Path(__file__).parent / "build_gen.py").read()
GLASS = re.search(r'BOTTLE_GLASS = """(.*?)"""', g, re.S).group(1)

SCENE = """THE SET — @image1. The bottle lies in the antique wooden spice drawer of @image1: the same type-case of square compartments with dark, worn, oiled wooden dividers, the same spices — brick-red paprika, burnt-orange paprika, dark caraway seeds, golden cumin and turmeric, pale ginger, saffron threads, pale green-white peppercorns, cinnamon powders, star anise and cinnamon sticks — and the same warm, rich palette of saffron red, ochre, cinnamon, umber and cream. The drawer, its compartments and its spices must be recognisably those of @image1; do not replace it with a table, a plain background or a different container."""

LOOK = """THE LOOK — AN AWARD-WINNING CAMPAIGN PHOTOGRAPH. This is the hero image of a luxury fragrance campaign, the kind of frame that wins a still-life award: bold, sensual, full of energy, yet completely real. Shot on a Phase One IQ4 150MP medium-format camera with a Schneider 120mm macro lens, lit with a single hard, warm key light (a bare strobe with a tungsten-balanced gel, about 3000K) from the upper-left at a low raking angle, plus a narrow strip light behind the drawer that rims the airborne spice from behind. Deep chiaroscuro: the bottle and the spices directly around it sit in a pool of warm light while the outer compartments fall away into rich, dark umber shadow. The motion is frozen by a 1/8000-second flash duration: every airborne grain, seed and fleck is tack-sharp, hanging in the air in a natural, chaotic arc, with the finest powder forming a soft, glowing cloud in the light beam. Real-photo character: subtle natural grain, true optical depth of field, slight lens falloff toward the corners, small dust specks in the air, irregular and unpredictable spice behaviour — clumps that break apart, grains that bounce off the glass, powder that slides down the curve. Nothing looks arranged or symmetrical; it looks caught in one fraction of a second."""

REALISM = """WHAT KEEPS IT REAL, NOT AI. The bottle has true weight and sits in the spice, sinking a few millimetres into the powder with a dense contact shadow. The spice that has already landed on it lies there physically: powder piled on the top of the curve and sliding down the sides in streaks, seeds resting at random angles, a few peppercorns trapped against the glass. Every airborne particle obeys the same hard light: lit on its upper-left side, rimmed from behind, casting tiny shadows where it is close to the glass. The glossy black glass reflects, softly and darkly, the falling spice and the warm light — reflections on its surface only. The label type reads as a warm cream, crisp and fully legible, with only a few grains near it. No plastic smoothness, no CGI particles, no perfect symmetry, no glowing outlines, no over-sharpening, no HDR."""

COMP = """COMPOSITION AND COLOUR. The composition follows a strong diagonal: the bottle and the flying spice run from the lower-left toward the upper-right, crossing the wooden dividers, which give the frame its graphic rhythm. The bottle sits on a third, not in the centre, leaving space in the direction the spice is moving. The brightest point of the frame is where the light hits the spice on the bottle's shoulder; the eye travels from there along the label to the cap. Colour: deep saturated paprika reds and ochres against the near-black glass, with the cream label type as the single light neutral; the darkest tones are a warm umber, never grey or blue. Textures are contrasted: matte, powdery spice against mirror-glossy black glass and satin brushed metal, worn grainy wood around them. Light quality: hard and directional on the spice so every grain throws a crisp micro-shadow, while the glossy glass shows one long clean highlight along its upper edge and a softer secondary reflection of the backlight along its lower edge. Depth: the plane of focus lies on the label; airborne particles nearest the lens are slightly soft, those beside the bottle sharp, those deeper in the drawer softly blurred, which gives the image its three-dimensional, tactile feel."""

NEG = """NEGATIVE / EXCLUSIONS. No transparent, tinted, amber, golden, brown, smoky or clear glass; nothing visible through the glass. No change of the bottle's shape, proportions, cap, label layout or text; no generic bottle; no oversized bottle — it is a real 100ml bottle, about one and a half compartments long. No spice hiding the words "COMMODITY" and "Spice". No hands, no spoons, no people, no extra bottles, no new props. No plain studio background, no table outside the drawer. No cartoonish explosion, no fire, no smoke, no sparks, no lens flare streaks. No AI look: no plastic surfaces, no fake-looking particle systems, no repeated identical grains. No misspelled, mirrored or warped text. No text overlays, watermarks or borders."""

FIN = "FINISH. One real, breathtaking photograph from the set of @image1 with the real bottle of @image2: one light, one moment frozen in time, every grain real. Portrait 4:5, 2K, photorealistic."

def build(intro, action):
    return "\n\n".join([intro, SCENE, action, GLASS, LOOK, COMP, REALISM, PRODUCT, FIN, NEG])
I = "A real, award-winning luxury fragrance campaign photograph for COMMODITY Spice: the real COMMODITY Spice bottle of @image2 in the spice drawer of @image1, with spices being thrown onto it, frozen in mid-air. Not an illustration, not a render, not a composite. Portrait 4:5, 2K."
V = {
"v5_1_paprika_pour": build(I, "THE SHOT — VARIATION 1, PAPRIKA CASCADE. Top-down, slightly closer than @image1. The bottle lies on its side across the brick-red paprika compartment, label up, cap toward the upper-right. From the top of the frame, a thick stream of brick-red paprika powder is being poured onto the bottle's shoulder: the stream hits the glass and bursts outward in a fan of red powder and fine dust that billows across the label's upper edge and the cap, while a soft red cloud hangs in the light above the glass. Powder has already piled up on the shoulder and slides down both sides in streaks. The surrounding compartments of caraway, peppercorns and cinnamon are dusted with stray red flecks."),
"v5_2_spice_burst": build(I, "THE SHOT — VARIATION 2, MIXED-SPICE IMPACT. Top-down. The bottle lies on its side across two compartments. A handful of whole spices has just been thrown onto it and is caught at the moment of impact: pale peppercorns bouncing off the glass and scattering in arcs, two or three star anise pods tumbling in the air, a spray of dark caraway seeds and saffron threads flying outward from the point of impact on the bottle's body, each with a crisp shadow on the spices below. A few peppercorns roll across the label's lower edge. The burst spreads diagonally across the frame, from the upper-left toward the lower-right."),
"v5_3_dust_beam": build(I, "THE SHOT — VARIATION 3, GOLDEN DUST IN THE LIGHT. The camera is lowered to about 30 degrees above the drawer, looking across the compartments, 120mm at f/5.6. The bottle lies on its side in the foreground compartment of paprika, half sunk in. A cloud of fine golden turmeric and cumin dust drifts down through the hard raking light just behind and above it, glowing warmly where the backlight catches it, while a few larger grains fall onto the cap and shoulder. The compartments behind dissolve into soft warm blur; the airborne dust gives depth and atmosphere."),
"v5_4_saffron_rain": build(I, "THE SHOT — VARIATION 4, SAFFRON AND PAPRIKA RAIN, MACRO. Top-down macro, 120mm at about 1:3: the frame shows the upper half of the bottle — cap, shoulder and the top of the label with \"COMMODITY\" and the full word \"Spice\" — lying in the paprika next to the caraway seeds. Fine red saffron threads and flecks of paprika rain down from above onto the black glass: some threads are still in the air, some have just landed and lie curled on the shoulder and cap, tiny powder puffs rising where they hit. Individual grains are resolved; the black glass shows their small dark reflections."),
}
ok=True
for n,t in V.items():
    pathlib.Path(n+".txt").write_text(t); l=len(t); ok&=10000<=l<=13000; print(n,l,"OK" if 10000<=l<=13000 else "OUT")
sys.exit(0 if ok else 1)
