# Hand scene, round 3: fixes oversized/floating/over-bright bottle. @image1 = hand scene, @image2 = bottle. 10,000-13,000 chars.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)

CRITICAL = """THE THREE RULES THAT DECIDE WHETHER THIS LOOKS REAL (read first, obey above everything else).
RULE 1 — REAL SIZE. The bottle is SMALL. It is a real 100ml perfume bottle about 11 cm tall and 6 cm wide, held by a real adult woman's hand. Use the apple in @image1 as the ruler: the whole bottle including its cap is only about 1.3 times as tall as the apple and slightly narrower than the apple. The bottle is never taller than the hand is long, never wider than the palm, never dominates the frame. In the frame the hand stays the main shape and the bottle sits inside it.
RULE 2 — REAL WEIGHT. The bottle physically rests in the hand. Its base sits deep in the cupped palm with no gap, the soft flesh of the palm bulges very slightly around the base, the fingers touch the glass, and a dense dark contact shadow fills the seam between glass and skin. It never floats, never hovers, never stands on top of the hand like a sticker.
RULE 3 — SAME LIGHT, LOW KEY. The bottle is lit only by the same weak, deep red light as everything else in @image1. It is mostly black and blends into the shadows: only its left edge, shoulder and cap rim catch thin, dull red highlights. The label is NOT bright: in this deep red light the white ink of "COMMODITY" and "Spice" reads as a muted salmon-red, about as bright as the lit skin of the palm, never brighter, never white, never glowing. The bottle is no sharper, no cleaner, no more contrasty than the hand. It must look as if it was in the model's hand when the shutter was pressed."""

SCENE = """WHAT @image1 CONTAINS — KEEP IT EXACTLY. This is an edit of @image1, not a new photo: same backdrop, same arm, same skin colour, same pose, same jewellery, same light, same grain. Background: deep maroon-black studio backdrop with a faint vertical fabric texture (#1A0204 to #050001), lifted only slightly around the hand. A woman's bare forearm enters from the left edge and extends horizontally to the right at the vertical middle of the frame, palm up, fingers together, gently curved, fingertips softly touching one another in a slow sensual gesture, long glossy almond nails pointing right. Generous black space above and below the hand, as in @image1. Skin under the red light: luminous coral-red to vermilion where lit (#F0463C highlights, #D42A28 midtones), dark red #8C1014 in creases and under the forearm. NO RINGS on any finger. Jewellery exactly as in @image1 and nothing else: a stack of about five thin bangles at the wrist; two very fine chains draped over the palm hanging straight down left of centre; a cluster of chains with small hammered coin discs hanging from the base of the fingers on the right. One soft red light from above, slightly in front and to camera-left, falling off to black below and to the right. Only red and black in the whole frame."""

TECH = """CAMERA (same as @image1): full-frame digital, about 85mm, eye-level, straight-on, f/4: hand and bottle sharp, chain ends and bangles slightly soft; faint luminance noise in the shadows; soft black vignette. Portrait 4:5 crop with the hand at the vertical centre and the same amount of black space around it as @image1."""

SKIN = """HAND REALISM. Identical hand to @image1: same size, finger length, nail shape and lacquer, same pose. Real skin: fine pores, creases at knuckles and across the palm, slight translucency at the fingertips, soft sheen — not waxy, not smoothed. One hand, five fingers, natural joints, thumb as in @image1, no rings."""

HOLD = """HOW THE HAND HOLDS THE BOTTLE — SENSUAL AND REAL. The hand truly holds the bottle; the bottle is part of the gesture, not placed near it. The pose stays the same elegant pose as @image1, but the fingers now close softly around the glass: slow, relaxed, intimate, almost a caress. Fingertips rest lightly on the glass with the pads touching it, the long glossy nails gliding along the curve of the bottle, one fingertip just grazing the edge of the label. The thumb rests against the near side of the glass. The grip is loose and tender, never a fist and never stiff: the knuckles soften, the fingers follow the cylinder's curve exactly, and each fingertip that touches the glass flattens very slightly where it meets it. Where fingers overlap the bottle they are in front of it; the glass behind them is hidden. The weight of the bottle is visible in the hand: the palm and wrist tilt a few degrees to carry it."""

INTEGRATION = """INTEGRATION CHECKLIST. (1) Scale per RULE 1 — compare with the apple and the hand before anything else. (2) Contact per RULE 2 — skin compresses, contact shadow, fingers touching glass. (3) Light per RULE 3 — the bottle is the darkest object in the hand; its right side melts into the black backdrop; highlights are thin and dull red, never white, silver or bright; no light falls on the bottle that does not also fall on the hand. (4) Reflections: the glossy black glass shows only a dim, blurred red reflection of the palm and fingers along its left curve — no transparency, no clear mirror image. (5) Chains: any fine chain touching the bottle rests on the glass with a tiny shadow. (6) Same capture: identical grain, focus, softness and colour cast on bottle and hand; the bottle edges are as soft as the finger edges, never cut out or haloed."""

NEGATIVE = """NEGATIVE / EXCLUSIONS. No oversized bottle: never larger than 1.3 times the apple, never larger than the hand. No floating bottle, no gap under the base, no missing contact shadow. No bright, white or glowing label text; no clean studio-lit product look; no bottle brighter or sharper than the hand; no halo or cut-out edge around the bottle. No rings. Do not change the hand pose, skin colour, bangles, chains, backdrop or light of @image1. Do not alter the bottle's shape, proportions, cap, label layout or text; no generic bottle. No transparency in the glass. No second light, no white or blue light. No extra or merged fingers. No plastic or waxy skin, no CGI look, no bloom. No misspelled or warped text. No extra bottles, no new props, no face. No text overlays, watermarks or borders."""

FINISH = "FINISH. Indistinguishable from an unretouched frame shot on the set of @image1, with the real COMMODITY Spice bottle of @image2 resting in the model's hand: one light, one colour, one grain, one moment, one whole image. Portrait 4:5, 2K, photorealistic."

def build(intro, placement, macro=False):
    parts = [intro, CRITICAL, SCENE] + ([] if macro else [TECH]) + [placement, HOLD, SKIN, PRODUCT, INTEGRATION, FINISH, NEGATIVE]
    return "\n\n".join(parts)

V1 = build(
"""A real photograph for the fragrance COMMODITY Spice: @image1 exactly as it is, with one change — the red apple in the palm is replaced by the real, small perfume bottle from @image2, standing in the hand. Not an illustration, not a render, not a composite. Portrait 4:5, 2K, photorealistic.""",
"""PLACEMENT (the only change). The apple is gone. In its exact place, the bottle stands upright in the cupped palm, its base sunk into the hollow of the palm just behind the fingers, its height about 1.3 times the apple's height (RULE 1). The softly touching fingers curve up against the lower third of the glass, the fingertips resting on the glass, cradling it. The label faces the camera squarely; "COMMODITY" and "Spice" are legible but dim, muted salmon-red (RULE 3). The two fine chains over the palm pass beside the base exactly where they lay in @image1; the coin chains on the right hang unchanged. The bottle's left edge and shoulder catch a thin dull red highlight from the upper-left light; its right half sinks into black. A short soft shadow falls from the bottle onto the fingers toward the lower right. The top of the cap stays well below the upper third of the frame.""")

V2 = build(
"""A real photograph for the fragrance COMMODITY Spice: a subtle variation of @image1 — same hand, same pose, same light, same colour — in which the real, small perfume bottle from @image2 lies on its side in the open palm instead of the apple. Not an illustration, not a render, not a composite. Portrait 4:5, 2K, photorealistic.""",
"""PLACEMENT (the only change). The apple is gone. The bottle lies horizontally in the palm, resting on its side along the length of the hand: its flat base nestled against the heel of the palm near the wrist, its cap pointing right toward the fingertips, its length about the same as the palm's width plus the first finger joints (RULE 1 — still only about 1.3 times the apple's height in length). The softly touching fingers curl gently up and over the far side of the cap and shoulder, fingertips resting on the glass, so the hand cradles the bottle the way it cradled the apple. The bottle is rotated so the label faces the camera; "COMMODITY" and "Spice" run along the bottle's length, legible but dim, muted salmon-red (RULE 3). The palm wraps slightly around the curve of the glass with a deep contact shadow along the whole underside (RULE 2). The red light from the upper-left lays one thin dull red highlight along the top edge of the lying cylinder; the bottom half sinks into black. The two fine chains drape over the bottle's base and hang down as in @image1; the coin chains on the right hang unchanged.""")

V3 = build(
"""A real macro photograph for the fragrance COMMODITY Spice, taken on the set of @image1 a moment after the real, small perfume bottle from @image2 was placed upright in the model's palm in place of the apple. Only the camera moves closer. Not an illustration, not a render, not a composite. Portrait 4:5, 2K, photorealistic.""",
"""MACRO FRAMING. 100mm macro at about 1:2, eye-level, f/5.6, a few centimetres from the glass. The frame shows only: the lower half of the label with the full word "Spice" (and "COMMODITY" above it if it fits), sharp and correctly spelled but dim, muted salmon-red (RULE 3); the base of the bottle sunk into the hollow of the palm with the skin compressing around it and a deep contact shadow in the seam (RULE 2); and from the right, the softly touching fingertips with long glossy almond nails resting against the glass in the same sensual gesture as @image1. One fine chain from the palm crosses the lower-left corner, out of focus. Everything outside a razor-thin plane of focus melts into smooth red and black blur. Light and materials at this scale: the same weak red light from upper-left draws one thin dull red streak along the left curve of the glossy black glass, which otherwise stays nearly black and reflects only a dim blurred red image of the fingertips; the label is matte uncoated paper with fine fibre texture and a clean die-cut edge; skin shows fingerprint ridges, fine creases, cuticles and the nail lacquer's small dull red reflection, the same colour as @image1. Grain, softness and colour cast identical on skin and bottle.""", macro=True)

ok = True
for name, text in [("v1_bottle_in_palm", V1), ("v2_bottle_lying_in_palm", V2), ("v3_macro", V3)]:
    pathlib.Path(f"{name}.txt").write_text(text)
    n = len(text); ok &= 10000 <= n <= 13000
    print(f"{name}: {n} chars", "OK" if 10000 <= n <= 13000 else "OUT OF RANGE")
sys.exit(0 if ok else 1)
