# Exact-recreation prompts for the red-lit hand scene: @image1 = hand scene, @image2 = bottle. Checks 10,000-13,000 chars.
import pathlib, re, sys
src = pathlib.Path(__file__).resolve().parent.parent / "commodity-spice" / "build.py"
PRODUCT = re.search(r'PRODUCT = """(.*?)"""', src.read_text(), re.S).group(1)

EDIT_RULE = """THIS IS AN EDIT OF @image1, NOT A NEW PHOTOGRAPH. Treat @image1 as the original RAW frame and keep it identical: the same hand, the same skin colour, the same finger pose, the same bangles, the same chains, the same background, the same light, the same grain, the same camera position. The only change allowed is the one described under PLACEMENT. Do not restage, re-pose, re-light, re-colour, beautify or "improve" anything that already exists in @image1."""

SCENE = """WHAT @image1 CONTAINS — REPRODUCE EXACTLY. Background: a deep maroon-black studio backdrop with a very faint vertical fabric texture, darkest at the edges and bottom, slightly lifted around the hand where the red light spills (#1A0204 to #050001). Arm and hand: a woman's bare forearm enters from the left edge at mid-height and extends horizontally to the right, palm turned up. The fingers are held together and gently curved, the fingertips softly meeting and resting against one another in a slow, sensual gesture — not spread, not gripping, relaxed and elegant — with long glossy almond-shaped nails pointing to the right. The wrist and forearm stay exactly at the same angle and height as in @image1. Skin colour under the red light: luminous coral-red to vermilion on the lit top surfaces (around #F0463C in highlights, #D42A28 in midtones), deepening to #8C1014 on the underside of the forearm and in the creases, with a soft natural sheen on the palm and fingers. NO RINGS: there are no rings on any finger — the fingers are bare. Jewellery that does exist: at the wrist on the left, a stack of about five thin metal bangles, catching thin red-gold highlights on their upper edges; two very fine chains draped over the palm hanging straight down to the left of the centre, ending low in the frame with tiny pendants; and on the right, from the base of the fingers, a cluster of chains with small hammered coin-shaped discs hanging down into the dark, glinting red-gold. Keep their exact number, length, position and the way they hang. Light: one soft red light from above and slightly in front, camera-left, lighting the tops of the arm, palm, fingers and objects and falling off to black below and to the right. Grade: everything is red and black only — no white, no orange, no neutral tones."""

TECH = """CAMERA (unchanged from @image1): full-frame digital capture, short telephoto around 85mm, eye-level, straight-on, moderate shallow depth of field (about f/4) so the hand and the objects in the palm are sharp while the lower ends of the chains and the bangles soften slightly; faint fine luminance noise in the shadows, soft black vignette. Output recomposed to a 4:5 portrait crop that keeps the whole hand, the bangles and the hanging chains inside the frame with the same black space around them as @image1."""

SKIN = """HAND REALISM (match @image1 exactly). Real skin, not CGI: fine pore texture on the back of the hand and wrist, delicate creases across the palm and at each finger joint, soft natural colour variation where the light thins out, the slight translucency of skin at the fingertips, cuticles and glossy nail lacquer with small sharp red reflections. Same hand, same size, same finger length and nail shape as @image1. Correct anatomy: one hand, five fingers, the thumb in the same position as in @image1, natural joints, no extra, missing or merged fingers, no rings."""

INTEGRATION = """INTEGRATION REALISM — THE BOTTLE MUST LOOK PHOTOGRAPHED IN THE HAND. (1) Same light: the red light from upper camera-left is the only light, so the opaque glossy black bottle shows one long, soft red specular highlight on its upper-left curvature and shoulder, a smaller red glint on the bevelled edge of the brushed cap, and its right side falls into black that melts into the backdrop. No white, silver or neutral highlight anywhere on the bottle. (2) Weight and contact: the bottle has real weight; the soft skin of the palm and fingers compresses slightly where it rests, and a dense, soft contact shadow sits exactly where glass meets skin. The fingers stay in their sensual touching pose, simply wrapping around the glass where they meet it. (3) Reflections: the glossy black glass mirrors a dark, blurred red image of the palm, fingertips and nearby chains on its curved surface — reflections only, never transparency. The matte label reflects nothing and shows a soft gradient, brighter on the left; its white type reads pale pinkish-red under the red light but stays fully legible. (4) Chains: where a fine chain touches the bottle it rests on the glass with a tiny shadow and a tiny reflection. (5) Matched capture: the bottle has exactly the same sharpness, noise, depth of field, red colour cast and contrast as the hand next to it — never cleaner, brighter, sharper or more neutral."""

NEGATIVE = """NEGATIVE / EXCLUSIONS. No rings on any finger. Do not change the hand pose, finger positions, skin colour, bangles, chains, background or light of @image1. Do not alter the bottle's shape, proportions, cap size, cap height, label size, label position, typeface or text; do not invent a new or generic bottle. No transparency anywhere in the glass. No floating bottle, no missing contact shadow, no second light source, no white or blue light. No extra, missing or merged fingers, no distorted nails. No plastic, waxy or over-smoothed skin, no CGI look, no bloom, no added glow. No gibberish, misspelled, mirrored or warped label text. No extra bottles, no new props, no face, no body other than the forearm and hand. No text overlays, watermarks or borders."""

FINISH = "FINISH. The result must be indistinguishable from an unretouched frame shot on the same set as @image1, seconds later, with the COMMODITY Spice bottle of @image2 physically in the model's hand: one light, one colour, one grain, one moment. Portrait 4:5 aspect ratio, 2K resolution, photorealistic."

def build(intro, placement, light, macro=False):
    rule = EDIT_RULE.replace(", the same camera position", ", only the camera moves closer") if macro else EDIT_RULE
    return "\n\n".join([intro, rule, SCENE] + ([] if macro else [TECH]) + [placement, light, SKIN, PRODUCT, INTEGRATION, FINISH, NEGATIVE])

V1 = build(
"""A real photograph for the fragrance COMMODITY Spice — an exact recreation of @image1 with one change: the red apple in the palm is replaced by the perfume bottle from @image2. Not an illustration, not a 3D render, not a composite. Output: portrait 4:5, 2K, photorealistic.""",
"""PLACEMENT (the only change). The apple is removed. In exactly the same place, the bottle stands upright on its flat base in the cupped palm, nestled between the palm and the softly touching fingers, the fingertips curving up against the lower part of the glass as if cradling it — the same gesture as in @image1, now holding the bottle. Its scale is that of a real 100ml bottle in an adult woman's hand: about as tall as the palm is long. The label faces the camera squarely so "COMMODITY" and "Spice" read horizontally. The two fine chains that cross the palm pass under and beside the base of the bottle exactly where they crossed in @image1.""",
"""LIGHT ON THE BOTTLE. The red light from upper camera-left draws one long, soft vertical highlight down the upper-left of the glossy black body and a curved glint across the left shoulder; the brushed cap shows fine horizontal brushing lit red on its left half and falls to black on the right. The bottle casts a short soft shadow onto the palm and fingers toward the lower right.""")

V2 = build(
"""A real photograph for the fragrance COMMODITY Spice — an exact recreation of @image1, with the apple kept, and the perfume bottle from @image2 added so the hand now holds both. Not an illustration, not a 3D render, not a composite. Output: portrait 4:5, 2K, photorealistic.""",
"""PLACEMENT (the only change). The apple stays exactly where it is in @image1, resting on the palm near the wrist. The bottle is added between the apple and the fingers: it lies on its side across the fingers, its base resting against the apple and its cap pointing to the right toward the fingertips, held in place by the softly touching fingers that curl gently over its far side — the fingertips meet each other on top of the glass in the same slow, sensual touch as @image1. The label faces up toward the camera so "COMMODITY" and "Spice" read along the bottle's long axis. Its scale is that of a real 100ml bottle in an adult woman's hand. The chains hang exactly as in @image1.""",
"""LIGHT ON THE BOTTLE. The red light from above camera-left lands on the upper side of the lying cylinder, drawing one long soft red highlight along its full length and a glint along the cap's bevel; the underside falls into black. The bottle casts a soft shadow onto the fingers below it and onto the apple's flank, and the apple's red skin is mirrored faintly in the black glass near the base.""")

V3 = build(
"""A real macro photograph for the fragrance COMMODITY Spice — an extreme close-up taken on the set of @image1, seconds after the bottle from @image2 was placed upright in the model's palm in place of the apple. Not an illustration, not a 3D render, not a composite. Output: portrait 4:5, 2K, photorealistic.""",
"""PLACEMENT AND MACRO FRAMING. Same hand, same pose, same light, same colour as @image1, but the camera moves in with a 100mm macro lens at about 1:2, eye-level, aperture f/5.6, so the frame shows only about 7 centimetres of the scene: the upper half of the matte black label with "COMMODITY" and the full word "Spice" completely in frame, sharp and correctly spelled; the glossy black glass shoulder and the lower edge of the brushed cap above it; and, curving in from the bottom-right, the softly touching fingertips with their long glossy almond nails resting against the glass in the same sensual gesture as @image1. One of the fine chains from the palm crosses the bottom-left corner, out of focus. Everything outside the thin plane of focus melts into smooth red and black blur.""",
"""LIGHT AND MATERIAL AT MACRO SCALE. The red light from upper camera-left sweeps one long soft highlight along the glass curvature and a sharp glint along the shoulder; the glass is opaque and mirror-smooth, reflecting a dark red image of the fingertips — nothing visible through it. Cap: fine circumferential brushing clearly resolved, glowing red on its left edge. Label: matte uncoated paper with subtle fibrous tooth, clean die-cut edge, white ink letterforms with sharp edges and slight real-print ink spread, reading pale red. Skin: fingerprint ridges, fine creases, cuticles and lacquer reflections, matching the skin colour of @image1 exactly.""", macro=True)

ok = True
for name, text in [("v1_exact_bottle_replaces_apple", V1), ("v2_exact_with_apple", V2), ("v3_macro", V3)]:
    pathlib.Path(f"{name}.txt").write_text(text)
    n = len(text); ok &= 10000 <= n <= 13000
    print(f"{name}: {n} chars", "OK" if 10000 <= n <= 13000 else "OUT OF RANGE")
sys.exit(0 if ok else 1)
